# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590f636d6dc574070e0beaeeea7b358cd936d3b2dbb70ff5a7dfb6c344b130a7a2cecec53e947a8167520ef7f0fe00e049b79d179d05f99927e16c439fdb1683

test:
  secret_key_base: 2a71ab770b093a70eeb0d2af0b644a44b70acac3657c025359fe5c261a9ac1cf3411dd379d9c580ef476e5e7ceb815373e21d7e7237b940ef986ad494ac6adcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
